# Custom Language File for Launcher Customizer

[ejs.app]
title = "沼ランチャー"

[ejs.landing]

[ejs.settings]
sourceGithubLink = "https://github.com/TeamKun/NumaLauncher"
supportLink = "https://discord.gg/kyefhuY5Rd"

[ejs.welcome]
welcomeHeader = "ようこそ、沼ランチャーへ"
welcomeDescription = "沼な人でもModが導入できる、そんなランチャーです。"
welcomeDescCTA = "数クリックでマイクラ参加型へ参加する準備が整います。"
