name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build (helios-core)
        run: |
          npm ci
          npm run build
        shell: bash
        working-directory: ./helios-core

      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Set npm version (only if different)
        shell: bash
        run: |
          CURRENT=$(node -p "require('./package.json').version")
          TARGET="${{ steps.get_version.outputs.version-without-v }}"
          if [ "$CURRENT" != "$TARGET" ]; then
            npm version "$TARGET" --no-git-tag-version
          else
            echo "Version already $TARGET, skipping"
          fi

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      - uses: actions/upload-artifact@v4
        name: Action-Upload
        with:
          name: windows-release
          path: |
            dist/latest*.yml
            dist/NumaLauncher-setup-${{ steps.get_version.outputs.version-without-v }}*

  release:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Get latest release version tag number
        id: get_version
        uses: battila7/get-version-action@v2

      - uses: actions/download-artifact@v4
        name: Action-Download
        with:
          path: dist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: NumaLauncher - ${{ steps.get_version.outputs.version }}
          body: |
            ### ▼ご使用のOSのインストーラーをダウンロードしてください。
            [Windows](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/NumaLauncher-setup-${{ steps.get_version.outputs.version-without-v }}.exe)

            ### ビルド情報
            ${{ steps.get_version.outputs.version }} by ${{ github.actor }}
          draft: false
          prerelease: false
          files: |
            dist/**/latest*.yml
            dist/**/NumaLauncher-setup-${{ steps.get_version.outputs.version-without-v }}*
